"""add data to yandex metric integration

Revision ID: 13d0f00521ed
Revises: 8986fd21f37f
Create Date: 2025-08-01 18:32:22.179756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13d0f00521ed'
down_revision: Union[str, Sequence[str], None] = '8986fd21f37f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yandex_metrika_integrations', sa.Column('goals', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('yandex_metrika_integrations', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yandex_metrika_integrations', 'data')
    op.drop_column('yandex_metrika_integrations', 'goals')
    # ### end Alembic commands ###
