"""add is_compared

Revision ID: 15e34d74c544
Revises: e9a3858064e6
Create Date: 2025-07-30 09:14:49.985329

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "15e34d74c544"
down_revision: Union[str, Sequence[str], None] = "e9a3858064e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reports",
        sa.Column("is_compared", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reports", "is_compared")
    # ### end Alembic commands ###
