"""add report compares

Revision ID: 54ade734336d
Revises: 15e34d74c544
Create Date: 2025-07-30 09:38:02.304906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ade734336d'
down_revision: Union[str, Sequence[str], None] = '15e34d74c544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_compares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_report_id', sa.UUID(), nullable=False),
    sa.Column('target_report_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_compares')
    # ### end Alembic commands ###
