"""add metrics integration

Revision ID: 61be00ff757f
Revises: a357be0b1dde
Create Date: 2025-07-31 17:04:42.765708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61be00ff757f'
down_revision: Union[str, Sequence[str], None] = 'a357be0b1dde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_ym_counter'), table_name='companies')
    op.drop_column('companies', 'ym_token')
    op.drop_column('companies', 'ym_counter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('ym_counter', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('ym_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_companies_ym_counter'), 'companies', ['ym_counter'], unique=True)
    # ### end Alembic commands ###
