"""remove unnessary fields

Revision ID: 8986fd21f37f
Revises: 61be00ff757f
Create Date: 2025-07-31 17:24:55.229880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8986fd21f37f'
down_revision: Union[str, Sequence[str], None] = '61be00ff757f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yandex_metrika_integrations', 'name')
    op.drop_column('yandex_metrika_integrations', 'description')
    op.drop_column('yandex_metrika_integrations', 'expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yandex_metrika_integrations', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('yandex_metrika_integrations', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('yandex_metrika_integrations', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
